### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by coding-alt** [soulteary/docker-stable-diffusion-taiyi#5]
Error verifying pickled file from /stable-diffusion-webui/models/Taiyi-Stable-Diffusion-1B-Chinese-v0.1//text_encoder/pytorch_model.bin:
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/safe.py", line 83, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/root/miniconda3/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/root/miniconda3/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "/stable-diffusion-webui/modules/safe.py", line 98, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, 'v'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Traceback (most recent call last):
  File "/stable-diffusion-webui/webui.py", line 202, in <module>
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
    webui()
  File "/stable-diffusion-webui/webui.py", line 146, in webui
    initialize()
  File "/stable-diffusion-webui/webui.py", line 82, in initialize
    modules.sd_models.load_model()
  File "/stable-diffusion-webui/modules/sd_models.py", line 246, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/modules/encoders/modules.py", line 171, in __init__
    self.transformer = BertModel.from_pretrained(version+"/text_encoder")
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2006, in from_pretrained
    loaded_state_dict_keys = [k for k in state_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by soulteary** [comment]
ref https://github.com/soulteary/docker-stable-diffusion-taiyi/issues/1
